In [1]:
import numpy as np
import pandas as pd

In [5]:
# 1. np.array() - Bir listeyi NumPy dizisine çevirir.
arr = np.array([1, 2, 3, 4, 5])
print("1. np.array():", arr)
arr


1. np.array(): [1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [6]:
# 2. np.zeros() - Belirtilen boyutta tüm elemanları 0 olan bir dizi oluşturur.
zeros_arr = np.zeros((3, 3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 3. np.ones() - Belirtilen boyutta tüm elemanları 1 olan bir dizi oluşturur.
ones_arr = np.ones((2, 4))
ones_arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# 4. np.linspace() - Belirtilen aralıkta eşit aralıklı sayılar içeren bir dizi oluşturur.
linspace_arr = np.linspace(0, 10, 5)
linspace_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
# 5. np.arange() - Belirtilen başlangıç ve bitiş arasında belirli bir adımla dizi oluşturur.
arange_arr = np.arange(0, 10, 2)
arange_arr

array([0, 2, 4, 6, 8])

In [12]:
# 6. np.random.rand() - 0 ile 1 arasında rastgele sayılardan oluşan bir dizi oluşturur.
random_arr = np.random.rand(3, 3)
random_arr

array([[0.9633946 , 0.8276171 , 0.97427388],
       [0.49552471, 0.59110682, 0.42646791],
       [0.4689051 , 0.86422959, 0.33053587]])

In [13]:
# 7. np.mean() - Bir dizinin ortalama değerini hesaplar.
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
mean_value

3.0

In [14]:
# 8. np.median() - Bir dizinin medyanını (ortanca değerini) hesaplar.
median_value = np.median(data)
median_value

3.0

In [15]:
# 9. np.std() - Bir dizinin standart sapmasını hesaplar.
std_value = np.std(data)
std_value

1.4142135623730951

In [16]:
# 10. np.dot() - İki matrisin çarpımını hesaplar.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix1, matrix2)
dot_product

array([[19, 22],
       [43, 50]])